//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2124802010277_LeTuanKiet_CuoiKy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiTap
    {
        public int IdBaiTap { get; set; }
        public string TenBaiTap { get; set; }
        public Nullable<int> TacGia { get; set; }
        public Nullable<int> SoLuotNop { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<double> DiemTrungBinh { get; set; }
        public Nullable<int> LuotThich { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
