//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2124802010277_LeTuanKiet_CuoiKy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThiSinh
    {
        public string IdKyThi { get; set; }
        public Nullable<int> IdThiSinh { get; set; }
        public Nullable<double> Diem { get; set; }
        public int IdChiTietThiSinh { get; set; }
        public Nullable<int> Dung { get; set; }
        public Nullable<int> Sai { get; set; }
        public Nullable<int> ChuaLam { get; set; }
    
        public virtual KyThi KyThi { get; set; }
    }
}
