//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2124802010277_LeTuanKiet_CuoiKy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public int IdNguoiDung { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> Gio { get; set; }
        public Nullable<int> RoomId { get; set; }
    }
}
