//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2124802010277_LeTuanKiet_CuoiKy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguPhap
    {
        public int IdNguPhap { get; set; }
        public Nullable<int> IdTacGia { get; set; }
        public string TenNguPhap { get; set; }
        public string MoTaNgan { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> LuotThich { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
    }
}
